# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d3aedf676eea2a00db2d05af08cce8a6faf7fb0a5f6fac5a4c12ce65b068bf9635909748700d712ca2bc2b3c60f9d7267c5a6971a529b9ea54326af8af808fb

test:
  secret_key_base: d59fc9fdbfa69993a0efaa8e8f1234ceee213e0c7413df8d69cef20969d0ebc10ac1c6472e9c10ba3110b1a0ca3437a5a59baa5b591359ed0f5b277a51609bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
